
        /*
                *  AUTO-GENERATED FILE.  DO NOT MODIFY. 
                *  
                *  This class was automatically generated by the 
                *  aapt tool from the resource data it found.  It  should not be modified by hand.  
        */
        
        /* Generated Code Do Not Modify */
        package org.allbinary.game.testgamedemo




        import java.lang.Object        
        
        
        import kotlin.Array
        import kotlin.reflect.KClass
        

open public class R
            : Object
         {
        
companion object {
            
open public class attr
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            *//*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class drawable
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val testgamedemo_icon: Int = 0x7f020000

    val testgamedemo_wait_256_by_256: Int = 0x7f020001
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class id
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val ad_area_bottom: Int = 0x7f060002

    val ad_area_left: Int = 0x7f060003

    val ad_area_right: Int = 0x7f060004

    val ad_area_top: Int = 0x7f060001

    val testgamedemo: Int = 0x7f060000

    val testgamedemo_gl: Int = 0x7f060005
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class layout
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val testgamedemo_ad_overlay_layout: Int = 0x7f030000

    val testgamedemo_gl_ad_overlay_layout: Int = 0x7f030001

    val testgamedemo_gl_layout: Int = 0x7f030002

    val testgamedemo_layout: Int = 0x7f030003
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class raw
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val error: Int = 0x7f040000

    val licenseinitdata: Int = 0x7f040001

    val partner: Int = 0x7f040002

    val select: Int = 0x7f040003

    val test: Int = 0x7f040004

    val testgamedemo_wait_256_by_256: Int = 0x7f040005

    val touch_button_128_by_128: Int = 0x7f040026

    val touch_button_64_by_64: Int = 0x7f040027

    val touch_button_down_arrow_128_by_128: Int = 0x7f04002a

    val touch_button_down_arrow_64_by_64: Int = 0x7f04002b

    val touch_button_generic_action_128_by_128: Int = 0x7f04002c

    val touch_button_generic_action_64_by_64: Int = 0x7f04002d

    val touch_button_start_128_by_128: Int = 0x7f040038

    val touch_button_start_64_by_64: Int = 0x7f040039

    val touch_button_strafe_left_arrow_128_by_128: Int = 0x7f04003a

    val touch_button_strafe_left_arrow_64_by_64: Int = 0x7f04003b

    val touch_button_strafe_right_arrow_128_by_128: Int = 0x7f04003c

    val touch_button_strafe_right_arrow_64_by_64: Int = 0x7f04003d

    val touch_button_turn_left_arrow_128_by_128: Int = 0x7f04003e

    val touch_button_turn_left_arrow_64_by_64: Int = 0x7f04003f

    val touch_button_turn_right_arrow_128_by_128: Int = 0x7f040040

    val touch_button_turn_right_arrow_64_by_64: Int = 0x7f040041

    val touch_button_up_arrow_128_by_128: Int = 0x7f040042

    val touch_button_up_arrow_64_by_64: Int = 0x7f040043

    val ouya_a: Int = 0x7f040012

    val ouya_key: Int = 0x7f040013

    val ouya_o: Int = 0x7f040014

    val ouya_u: Int = 0x7f040015

    val ouya_y: Int = 0x7f040016
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class string
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val progressbar_in_title_string: Int = 0x7f050001

    val testgamedemo_app_name: Int = 0x7f050000
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
        }
            
            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            

