
        /*
                *  AUTO-GENERATED FILE.  DO NOT MODIFY. 
                *  
                *  This class was automatically generated by the 
                *  aapt tool from the resource data it found.  It  should not be modified by hand.  
        */
        
        /* Generated Code Do Not Modify */
        package org.allbinary.game.testgamedemo




        import java.lang.Object        
        
        
        import kotlin.Array
        import kotlin.reflect.KClass
        

open public class R
            : Object
         {
        
companion object {
            
open public class attr
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            *//*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class drawable
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val testgamedemo_icon: Int = 0x7f020011

    val testgamedemo_wait_256_by_256: Int = 0x7f020012
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class id
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val ad_area_bottom: Int = 0x7f060002

    val ad_area_left: Int = 0x7f060003

    val ad_area_right: Int = 0x7f060004

    val ad_area_top: Int = 0x7f060001

    val root: Int = 0x7f060005

    val testgamedemo: Int = 0x7f060000

    val testgamedemo_gl: Int = 0x7f060007
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class layout
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val testgamedemo_ad_overlay_layout: Int = 0x7f030000

    val testgamedemo_gl_ad_overlay_layout: Int = 0x7f030001

    val testgamedemo_gl_layout: Int = 0x7f030002

    val testgamedemo_layout: Int = 0x7f030003

    val testgamedemo_min3d_ad_overlay_layout: Int = 0x7f030004

    val testgamedemo_min3d_layout: Int = 0x7f030005
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class raw
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val error: Int = 0x7f040000

    val threed_obj: Int = 0x7f040029

    val simple_vertex_shader_gsn_glsl: Int = 0x7f030099

    val simple_texture_fragment_shader_gsn_glsl: Int = 0x7f030098

    val like2_fixed_pipeline_lighting_vertex_shader_glsl: Int = 0x7f030099

    val like2_fixed_pipeline_lighting_fragment_shader_glsl: Int = 0x7f030098

    val licenseinitdata: Int = 0x7f040008

    val locked_demo_game_feature_128_by_128: Int = 0x7f040009

    val locked_demo_game_feature_64_by_64: Int = 0x7f04000a

    val ouya_a: Int = 0x7f04000d

    val ouya_o: Int = 0x7f04000e

    val ouya_u: Int = 0x7f04000f

    val ouya_y: Int = 0x7f040010

    val partner: Int = 0x7f040011

    val select: Int = 0x7f040013

    val test: Int = 0x7f040014

    val testgamedemo_wait_256_by_256: Int = 0x7f040015

    val touch_button_128_by_128: Int = 0x7f040017

    val touch_button_64_by_64: Int = 0x7f040018

    val touch_button_down_arrow_128_by_128: Int = 0x7f040019

    val touch_button_down_arrow_64_by_64: Int = 0x7f04001a

    val touch_button_generic_action_128_by_128: Int = 0x7f04001b

    val touch_button_generic_action_64_by_64: Int = 0x7f04001c

    val touch_button_start_128_by_128: Int = 0x7f04001d

    val touch_button_start_64_by_64: Int = 0x7f04001e

    val touch_button_strafe_left_arrow_128_by_128: Int = 0x7f04001f

    val touch_button_strafe_left_arrow_64_by_64: Int = 0x7f040020

    val touch_button_strafe_right_arrow_128_by_128: Int = 0x7f040021

    val touch_button_strafe_right_arrow_64_by_64: Int = 0x7f040022

    val touch_button_turn_left_arrow_128_by_128: Int = 0x7f040023

    val touch_button_turn_left_arrow_64_by_64: Int = 0x7f040024

    val touch_button_turn_right_arrow_128_by_128: Int = 0x7f040025

    val touch_button_turn_right_arrow_64_by_64: Int = 0x7f040026

    val touch_button_up_arrow_128_by_128: Int = 0x7f040027

    val touch_button_up_arrow_64_by_64: Int = 0x7f040028
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
open public class string
            : Object
         {
        
/*Static stuff is not allowed for Kotlin inner classescompanion object {
            */
    val progressbar_in_title_string: Int = 0x7f050001

    val testgamedemo_app_name: Int = 0x7f050000
/*
        }
            */


            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            
        }
            
            //Auto Generated
            public constructor() : super()
            {
            }            
        
}
                
            

